{"name": "Login", "status": "broken", "statusDetails": {"message": "TypeError: 'str' object is not callable\n", "trace": "  File \"C:\\Users\\Vigne\\PycharmProjects\\Behave_Feb23\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Vigne\\PycharmProjects\\Behave_Feb23\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\StepDefn.py\", line 30, in the_user_enters_valid_credentials\n    lp.password_textbox_id(\"secret_sauce\")\n"}, "steps": [{"name": "Given the user launches the application", "status": "passed", "start": 1676090055851, "stop": 1676090057581}, {"name": "When the user verifies the logo", "status": "passed", "start": 1676090057581, "stop": 1676090057715}, {"name": "Then the user enters valid credentials", "status": "broken", "statusDetails": {"message": "TypeError: 'str' object is not callable\n", "trace": "  File \"C:\\Users\\Vigne\\PycharmProjects\\Behave_Feb23\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Vigne\\PycharmProjects\\Behave_Feb23\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\StepDefn.py\", line 30, in the_user_enters_valid_credentials\n    lp.password_textbox_id(\"secret_sauce\")\n"}, "start": 1676090057715, "stop": 1676090057862}], "start": 1676090055849, "stop": 1676090057863, "uuid": "a53d53c8-d014-4793-ae95-14b60baaa269", "historyId": "8fa95ae9eb30e067568b09ee12827b5a", "fullName": "Add to Cart: Login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Add to Cart"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}